// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lk_RTM
List lk_RTM(NumericVector th, DataFrame data, int nc1, int nc2, int J);
RcppExport SEXP _RTMLC_lk_RTM(SEXP thSEXP, SEXP dataSEXP, SEXP nc1SEXP, SEXP nc2SEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type th(thSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type nc1(nc1SEXP);
    Rcpp::traits::input_parameter< int >::type nc2(nc2SEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_RTM(th, data, nc1, nc2, J));
    return rcpp_result_gen;
END_RCPP
}
// lk_RTMLC
List lk_RTMLC(NumericVector th, DataFrame data, int nc1, int nc2, int J, int k1, int k2);
RcppExport SEXP _RTMLC_lk_RTMLC(SEXP thSEXP, SEXP dataSEXP, SEXP nc1SEXP, SEXP nc2SEXP, SEXP JSEXP, SEXP k1SEXP, SEXP k2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type th(thSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type nc1(nc1SEXP);
    Rcpp::traits::input_parameter< int >::type nc2(nc2SEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type k1(k1SEXP);
    Rcpp::traits::input_parameter< int >::type k2(k2SEXP);
    rcpp_result_gen = Rcpp::wrap(lk_RTMLC(th, data, nc1, nc2, J, k1, k2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RTMLC_lk_RTM", (DL_FUNC) &_RTMLC_lk_RTM, 5},
    {"_RTMLC_lk_RTMLC", (DL_FUNC) &_RTMLC_lk_RTMLC, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_RTMLC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
