# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lk_RTM <- function(th, data, nc1, nc2, J) {
    .Call(`_RTMLC_lk_RTM`, th, data, nc1, nc2, J)
}

lk_RTMLC <- function(th, data, nc1, nc2, J, k1, k2) {
    .Call(`_RTMLC_lk_RTMLC`, th, data, nc1, nc2, J, k1, k2)
}

